### PR TITLE
Add Dockerfile for multiplatform build.

### PR DESCRIPTION
**Pull request by Gronis**
Adding a Dockerfile so that building the project from scratch is very easy. This also makes building from a macOS or Windows system much easier.

### CODE REVIEW

**Comment by Lorenzooone** [comment]
Looks fine at a first glance. Though I plan to take a closer look into it in a week, while also adding support for DS builds. (And doing a full test of the -flto change I recently made)

**Comment by Gronis** [comment]
Great! Sounds like good changes.

**Comment by Gronis** [comment]
I've added support for both NDS and GBA when building in docker. Tested on docker running on linux with x86_64 and macos using docker desktop with aarch64 (M1/M2 Apple Silicon) with locked versions of `agbabi` and `blocksds`.

One nice thing I can think of is that it would be nice to put the docker stuff into the make file so if you run `make` it will try to build on host if it has the necessary dependencies installed. If not, it will try with docker instead. But since there are different Makefiles for nds and gba versions, I decided not to do anything like that. E.g, I don't really know how you would like to structure the Makefiles.

**Comment by Lorenzooone** [comment]
Updated to use separate builders for GBA and NDS, to keep them separate.
There is currently a bug with the NDS title. It's been filed to blocksds https://github.com/blocksds/sdk/issues/86. Once that is fixed, I'll reupload the docker image.

**Pull request merged**
